/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ar.vega.gonzalo.vista;

import ar.vega.gonzalo.customUI.CustomButton;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Gonzalo Vega <ar.vega.gonzalo>
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    public JButton getBtnAlumnos() {
        return btnAlumnos;
    }

    public CustomButton getBtnMaterias() {
        return btnMaterias;
    }

    public void setJpCenter(JPanel jpCenter) {
        this.jpCenter = jpCenter;
    }

    public CustomButton getBtnCursado() {
        return btnCursado;
    }
    

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnMaterias = new ar.vega.gonzalo.customUI.CustomButton();
        btnAlumnos = new ar.vega.gonzalo.customUI.CustomButton();
        btnCursado = new ar.vega.gonzalo.customUI.CustomButton();
        jpCenter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestion");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 10));

        btnMaterias.setForeground(new java.awt.Color(0, 0, 0));
        btnMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/book-stack.png"))); // NOI18N
        btnMaterias.setToolTipText("Materias");
        btnMaterias.setFont(new java.awt.Font("Noto Mono", 0, 13)); // NOI18N
        btnMaterias.setRadius(60);
        jPanel3.add(btnMaterias);

        btnAlumnos.setForeground(new java.awt.Color(0, 0, 0));
        btnAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/group.png"))); // NOI18N
        btnAlumnos.setToolTipText("Alumnos y Profesores");
        btnAlumnos.setFont(new java.awt.Font("Noto Mono", 0, 13)); // NOI18N
        btnAlumnos.setRadius(75);
        jPanel3.add(btnAlumnos);

        btnCursado.setForeground(new java.awt.Color(0, 0, 0));
        btnCursado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/courses.png"))); // NOI18N
        btnCursado.setToolTipText("Cursados");
        btnCursado.setFont(new java.awt.Font("Noto Mono", 0, 13)); // NOI18N
        btnCursado.setRadius(75);
        jPanel3.add(btnCursado);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jpCenter.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Noto Mono", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/utn.png"))); // NOI18N
        jLabel1.setText("Sistema De Gestión de Alumnos");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(20);
        jLabel1.setOpaque(true);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jpCenterLayout = new javax.swing.GroupLayout(jpCenter);
        jpCenter.setLayout(jpCenterLayout);
        jpCenterLayout.setHorizontalGroup(
            jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCenterLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jpCenterLayout.setVerticalGroup(
            jpCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCenterLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        getContentPane().add(jpCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ar.vega.gonzalo.customUI.CustomButton btnAlumnos;
    private ar.vega.gonzalo.customUI.CustomButton btnCursado;
    private ar.vega.gonzalo.customUI.CustomButton btnMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpCenter;
    // End of variables declaration//GEN-END:variables
}
